services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    command: postgres -c "pg_stat_statements.track=all" -c "shared_preload_libraries=pg_stat_statements"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=aljam3
      - POSTGRES_PASSWORD=aljam3
      - POSTGRES_DB=aljam3_development

  memcached:
    image: memcached:1.6.38
    restart: unless-stopped
    ports:
      - "11212:11211"
    volumes:
      - memcached-data:/var/lib/memcached/data

  meilisearch:
    image: getmeili/meilisearch:v1.14.0
    restart: unless-stopped
    ports:
      - "7701:7700"
    volumes:
      - meilisearch-data:/meili_data

volumes:
  postgres-data:
  memcached-data:
  meilisearch-data:
