services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    command: postgres -c "shared_preload_libraries=pg_stat_statements" -c "pg_stat_statements.track=all" -c "pg_stat_statements.max=10000" -c "track_activity_query_size=2048"
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=aljam3
      - POSTGRES_PASSWORD=aljam3
      - POSTGRES_DB=aljam3_development

  meilisearch:
    image: getmeili/meilisearch:v1.14.0
    restart: unless-stopped
    ports:
      - "7701:7700"
    volumes:
      - meilisearch-data:/meili_data

volumes:
  postgres-data:
  meilisearch-data:
