min_version = "2025.5.11"

[env]
PROJECT_NAME = "{{ config_root | basename }}"

[tools]
ruby = "{{ get_env(name='RUBY_VERSION', default='3.4.4') }}"
node = "{{ get_env(name='NODE_VERSION', default='24.1.0') }}"
yarn = "4.9.1"
gh = "latest"

[tasks."docker:start"]
description = "Start Docker services using docker-compose"
run = "docker compose -f dev-docker-compose.yml up -d"

[tasks."docker:stop"]
description = "Stop Docker services using docker-compose"
run = "docker compose -f dev-docker-compose.yml down"

[tasks."deps:js"]
description = "Install JavaScript dependencies"
run = "yarn install"

[tasks."deps:ruby"]
description = "Install Ruby gems"
run = "bundle install"

[tasks."db:prepare"]
description = "Prepare database (create and migrate)"
run = "bundle exec rails db:create db:migrate"

[tasks.test]
description = "Run tests using RSpec"
run = "CI=1 bundle exec rspec"

[tasks.lint]
description = "Run lint using Rubocop"
run = "bundle exec rubocop"

[tasks.dev]
description = "Start development environment"
run = '''
#!/bin/bash
set -e

mise run docker:start
mise run deps:js
mise run deps:ruby
mise run db:prepare

cleanup() {
  mise docker:stop

  exit 0
}

# Set up trap to call cleanup on SIGINT (Ctrl+C) and SIGTERM
trap cleanup SIGINT SIGTERM

echo
echo -e "\033[0;36m╔══════════════════════════════════════════════════════════╗\033[0m"
echo -e "\033[0;36m║                🚀 Development Environment 🚀             ║\033[0m"
echo -e "\033[0;36m╚══════════════════════════════════════════════════════════╝\033[0m"
echo

./bin/dev

cleanup
'''
