production:
  capture_query_stats:
    command: "PgHero.capture_query_stats"
    schedule: every 5 minutes
  capture_space_stats:
    command: "PgHero.capture_space_stats"
    schedule: every 5 minutes
